name: Actualizar Jugadores eFootball

on:
  schedule:
    - cron: '0 10 * * 4'
  workflow_dispatch:

permissions:  # ESTO ES LO MÁS IMPORTANTE
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add players.json
          git commit -m "Auto-update players" || exit 0
          git push
